In [101]:
import json
import requests
import pandas as pd
import numpy as np

In [24]:
api_key = 'RGAPI-fb3a0713-6548-42f1-b34a-a21b6bb36571'     #사용할때마다 새로 갱신
request_header = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept-Charset": "application/x-www-form-urlencoded; charset=UTF-8",
    "Origin": "https://developer.riotgames.com",
    "X-Riot-Token": "RGAPI-fb3a0713-6548-42f1-b34a-a21b6bb36571"
}
sohwan = "https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/" +'dbstjddlfz' +'?api_key=' + api_key
r = requests.get(sohwan, headers=request_header)
r.json()

{'id': 'djONZ7VGDbp5yU_bZkbD_Hw-77GL-RFpBBtFWSKCm5tq0w',
 'accountId': 'Xzn2JYE8r2VSoQX8znd9tk1u6VIZquTdiRsMvhLj7JFF',
 'puuid': 'zqsF9wUGSz3XjCslNnjI5u1yE9oUhmCfOimFVzSCVs9nYoEefROOwmgxcxYpCCngzJOmoHrQP3lvsg',
 'name': 'dbstjddlfz',
 'profileIconId': 4490,
 'revisionDate': 1652668678000,
 'summonerLevel': 113}

In [20]:
puuid = 'zqsF9wUGSz3XjCslNnjI5u1yE9oUhmCfOimFVzSCVs9nYoEefROOwmgxcxYpCCngzJOmoHrQP3lvsg'

In [118]:
match_id = 'https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/'+puuid+'/ids?start=0&count=100'
r = requests.get(match_id, headers=request_header)
matchid = []
matchid.append(r.json())
matchid

[['KR_5922952252',
  'KR_5922875558',
  'KR_5922891052',
  'KR_5919551036',
  'KR_5919511860',
  'KR_5919418742',
  'KR_5919406640',
  'KR_5919423347',
  'KR_5919298858',
  'KR_5919296866',
  'KR_5919272318',
  'KR_5917616050',
  'KR_5909495215',
  'KR_5902853619',
  'KR_5902538869',
  'KR_5902514536',
  'KR_5902431454',
  'KR_5902348700',
  'KR_5902326148',
  'KR_5902284770',
  'KR_5902350787',
  'KR_5902320050',
  'KR_5899697177',
  'KR_5899687667',
  'KR_5899683827',
  'KR_5897345108',
  'KR_5897037072',
  'KR_5895982655',
  'KR_5895683798',
  'KR_5895661345',
  'KR_5891090281',
  'KR_5891054463',
  'KR_5890753354',
  'KR_5890655413',
  'KR_5890039573',
  'KR_5889812624',
  'KR_5889632802',
  'KR_5888302590',
  'KR_5887852825',
  'KR_5887852080',
  'KR_5887900754',
  'KR_5887080727',
  'KR_5886928114',
  'KR_5886879372',
  'KR_5886853730',
  'KR_5886048240',
  'KR_5885969928',
  'KR_5885647563',
  'KR_5885451017',
  'KR_5885318425',
  'KR_5885228971',
  'KR_5885264645',
  'KR_5885273404',
  'KR_5885084582',
  'KR_5885035319',
  'KR_5885132751',
  'KR_5884084243',
  'KR_5884100814',
  'KR_5884026261',
  'KR_5884073138',
  'KR_5884070698',
  'KR_5883869003',
  'KR_5883867530',
  'KR_5878805004',
  'KR_5877830618',
  'KR_5877183749',
  'KR_5877030203',
  'KR_5876978613',
  'KR_5876821070',
  'KR_5876125608',
  'KR_5876096712',
  'KR_5876063484',
  'KR_5876031846',
  'KR_5876041166',
  'KR_5875789978',
  'KR_5875787599',
  'KR_5875786917',
  'KR_5875825896',
  'KR_5875814832',
  'KR_5875814118',
  'KR_5874889617',
  'KR_5874876349',
  'KR_5874809216',
  'KR_5874817006',
  'KR_5874794141',
  'KR_5874821890',
  'KR_5874649117',
  'KR_5874717263',
  'KR_5873379868',
  'KR_5873387859',
  'KR_5873415570',
  'KR_5873422889',
  'KR_5849920597',
  'KR_5849805473',
  'KR_5849779958',
  'KR_5849706252',
  'KR_5849700620',
  'KR_5846053404',
  'KR_5845943393',
  'KR_5825624520']]

In [88]:
match_df = 'https://asia.api.riotgames.com/lol/match/v5/matches/KR_5922952252/timeline'   #가장 최근했던 경기 불러오기
r = requests.get(match_df, headers=request_header)
df = pd.DataFrame(r.json())

In [114]:
df

,metadata,info
dataVersion,2,NaN
matchId,KR_5922952252,NaN
participants,[qSK3gwWMksjVTNELCthHrXZELyrujjEAltOqchyTH7Eq8...,"[{'participantId': 1, 'puuid': 'qSK3gwWMksjVTN..."
frameInterval,NaN,60000
frames,NaN,"[{'events': [{'realTimestamp': 1652881685344, ..."
gameId,NaN,5922952252

In [119]:
pd.DataFrame(df['info']['participants'])   #경기를 진행했던 10명의 puuid 정보

   participantId                                              puuid
0              1  qSK3gwWMksjVTNELCthHrXZELyrujjEAltOqchyTH7Eq8f...
1              2  H2ne7l6n8z36P5iL7xKj0q9FE91EKNIK3Zqhcack739ekb...
2              3  busgetln6mUxzW7k1yqV8jIv4lA34YqqERbj-P9p7QRC0W...
3              4  pq-k1UnrsOQ91xYRGzwIe-zF-s8M3kTW2wZLhljzqH08Oa...
4              5  ziBoEQhgKW79iI9icR4ABGHfHuhB37opYr0KkyBU_ZgXrL...
5              6  o5CMWGkL6cnyVVMVZzlQJNXrZZOJMSASRfROeGqx5LZm2X...
6              7  zqsF9wUGSz3XjCslNnjI5u1yE9oUhmCfOimFVzSCVs9nYo...
7              8  veozWiQ78wHnLs05VT3i_C2Z6qWkWyICrfJ4B2v-Yt-ppY...
8              9  DcJ6hOC_uAkUpk7g8UQTSOXenX0LKP7Jc6mZeV1tSYyRsu...
9             10  51I0_sMq4GczbEr0dLSwl2H-_sy9uqXob55MRpliNK170A...

In [123]:
pd.DataFrame(df['info']['frames'])   #op.gg 참고  총경기시간 34분18초 분단위로 확인가능 timestamp 1000당 1초로 기록된다

,events,participantFrames,timestamp
0,"[{'realTimestamp': 1652881685344, 'timestamp':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",0
1,"[{'levelUpType': 'NORMAL', 'participantId': 4,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",60022
2,"[{'levelUpType': 'NORMAL', 'participantId': 2,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",120039
3,"[{'level': 2, 'participantId': 8, 'timestamp':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",180050
4,"[{'levelUpType': 'NORMAL', 'participantId': 7,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",240057
5,"[{'afterId': 0, 'beforeId': 1027, 'goldGain': ...","{'1': {'championStats': {'abilityHaste': 0, 'a...",300062
6,"[{'levelUpType': 'NORMAL', 'participantId': 9,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",360069
7,"[{'level': 6, 'participantId': 6, 'timestamp':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",420075
8,"[{'levelUpType': 'NORMAL', 'participantId': 9,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",480098
9,"[{'itemId': 2055, 'participantId': 1, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",540102
10,"[{'itemId': 6660, 'participantId': 10, 'timest...","{'1': {'championStats': {'abilityHaste': 0, 'a...",600108
11,"[{'itemId': 3858, 'participantId': 5, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",660114
12,"[{'level': 9, 'participantId': 3, 'timestamp':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",720133
13,"[{'assistingParticipantIds': [5], 'bounty': 30...","{'1': {'championStats': {'abilityHaste': 0, 'a...",780134
14,"[{'assistingParticipantIds': [10], 'bounty': 3...","{'1': {'championStats': {'abilityHaste': 0, 'a...",840153
15,"[{'itemId': 2055, 'participantId': 9, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",900170
16,"[{'itemId': 1001, 'participantId': 5, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",960177
17,"[{'levelUpType': 'NORMAL', 'participantId': 9,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1020185
18,"[{'assistingParticipantIds': [2, 6, 10], 'boun...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1080194
19,"[{'itemId': 2055, 'participantId': 1, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1140196
20,"[{'itemId': 3859, 'participantId': 10, 'timest...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1200214
21,"[{'creatorId': 6, 'timestamp': 1201073, 'type'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1260228
22,"[{'itemId': 1029, 'participantId': 7, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1320247
23,"[{'itemId': 1026, 'participantId': 2, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1380252
24,"[{'creatorId': 6, 'timestamp': 1380821, 'type'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1440257
25,"[{'itemId': 2420, 'participantId': 8, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1500260
26,"[{'levelUpType': 'NORMAL', 'participantId': 9,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1560266
27,"[{'itemId': 1029, 'participantId': 7, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1620280
28,"[{'levelUpType': 'NORMAL', 'participantId': 7,...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1680297
29,"[{'itemId': 1028, 'participantId': 7, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1740302
30,"[{'itemId': 2055, 'participantId': 4, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1800332
31,"[{'assistingParticipantIds': [6, 7], 'bounty':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1860338
32,"[{'killerId': 8, 'timestamp': 1863396, 'type':...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1920363
33,"[{'itemId': 3145, 'participantId': 4, 'timesta...","{'1': {'championStats': {'abilityHaste': 0, 'a...",1980364
34,"[{'creatorId': 6, 'timestamp': 1980901, 'type'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",2040396
35,"[{'assistingParticipantIds': [7, 10], 'bounty'...","{'1': {'championStats': {'abilityHaste': 0, 'a...",2057956

In [126]:
#10명의 참가자 정보가 나와있다
pd.DataFrame(pd.DataFrame(df['info']['frames'])['participantFrames'][0])

,1,2,3,4,5,6,7,8,9,10
championStats,"{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'...","{'abilityHaste': 0, 'abilityPower': 0, 'armor'..."
currentGold,500,500,500,500,500,500,500,500,500,500
damageStats,"{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp...","{'magicDamageDone': 0, 'magicDamageDoneToChamp..."
goldPerSecond,0,0,0,0,0,0,0,0,0,0
jungleMinionsKilled,0,0,0,0,0,0,0,0,0,0
level,1,1,1,1,1,1,1,1,1,1
minionsKilled,0,0,0,0,0,0,0,0,0,0
participantId,1,2,3,4,5,6,7,8,9,10
position,"{'x': 554, 'y': 581}","{'x': 557, 'y': 345}","{'x': 335, 'y': 269}","{'x': 194, 'y': 457}","{'x': 329, 'y': 650}","{'x': 14180, 'y': 14271}","{'x': 14176, 'y': 14506}","{'x': 14398, 'y': 14582}","{'x': 14539, 'y': 14394}","{'x': 14404, 'y': 14201}"
timeEnemySpentControlled,0,0,0,0,0,0,0,0,0,0
totalGold,500,500,500,500,500,500,500,500,500,500
xp,0,0,0,0,0,0,0,0,0,0

In [127]:
pd.DataFrame(pd.DataFrame(df['info']['frames'])['events'][0])

   realTimestamp  timestamp       type
0  1652881685344          0  PAUSE_END

In [130]:
pd.DataFrame(pd.DataFrame(df['info']['frames'])['events'][1]) #0 타입이 pause_end(로딩) 1 0~59.9초 사이정보

,levelUpType,participantId,skillSlot,timestamp,type,itemId,afterId,beforeId,goldGain
0,NORMAL,4,1.0,2520,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN
1,NaN,3,NaN,3181,ITEM_PURCHASED,3070.0,NaN,NaN,NaN
2,NaN,3,NaN,3181,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
3,NaN,3,NaN,3181,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
4,NaN,6,NaN,3874,ITEM_PURCHASED,1056.0,NaN,NaN,NaN
5,NaN,1,NaN,4272,ITEM_PURCHASED,1054.0,NaN,NaN,NaN
6,NaN,6,NaN,4767,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
7,NaN,1,NaN,4800,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
8,NaN,6,NaN,5130,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
9,NaN,10,NaN,5229,ITEM_PURCHASED,3858.0,NaN,NaN,NaN
10,NaN,10,NaN,5229,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
11,NaN,10,NaN,5229,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
12,NaN,6,NaN,5725,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
13,NaN,1,NaN,5725,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
14,NaN,10,NaN,5956,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
15,NaN,7,NaN,5989,ITEM_PURCHASED,1039.0,NaN,NaN,NaN
16,NaN,7,NaN,6816,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
17,NaN,7,NaN,7246,ITEM_PURCHASED,2031.0,NaN,NaN,NaN
18,NaN,4,NaN,7279,ITEM_PURCHASED,1055.0,NaN,NaN,NaN
19,NaN,4,NaN,7279,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
20,NaN,2,NaN,7807,ITEM_PURCHASED,2031.0,NaN,NaN,NaN
21,NaN,4,NaN,8171,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
22,NaN,2,NaN,8370,ITEM_PURCHASED,1035.0,NaN,NaN,NaN
23,NaN,8,NaN,9229,ITEM_PURCHASED,1056.0,NaN,NaN,NaN
24,NaN,8,NaN,9229,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
25,NaN,8,NaN,9229,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
26,NORMAL,7,1.0,9461,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN
27,NaN,4,NaN,9528,ITEM_UNDO,NaN,3340.0,0.0,0.0
28,NaN,4,NaN,9660,ITEM_UNDO,NaN,0.0,2003.0,50.0
29,NaN,4,NaN,9792,ITEM_UNDO,NaN,0.0,1055.0,450.0
30,NaN,8,NaN,9924,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
31,NaN,5,NaN,10023,ITEM_PURCHASED,3858.0,NaN,NaN,NaN
32,NaN,4,NaN,11740,ITEM_PURCHASED,3070.0,NaN,NaN,NaN
33,NaN,5,NaN,12665,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
34,NaN,5,NaN,12830,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
35,NaN,4,NaN,13193,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
36,NaN,5,NaN,13259,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
37,NaN,4,NaN,13425,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
38,NORMAL,3,1.0,13623,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN
39,NaN,4,NaN,13887,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
40,NaN,9,NaN,14085,ITEM_PURCHASED,1036.0,NaN,NaN,NaN
41,NaN,9,NaN,14085,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
42,NaN,9,NaN,14085,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
43,NaN,9,NaN,14085,ITEM_PURCHASED,2003.0,NaN,NaN,NaN
44,NaN,9,NaN,14845,ITEM_PURCHASED,3340.0,NaN,NaN,NaN
45,NORMAL,5,1.0,20830,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN
46,NORMAL,8,1.0,29986,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN

In [135]:
pd.DataFrame(df['info']['frames'])['events'].apply(lambda x: pd.DataFrame(x)['type']).T  #시간별 이벤트정보

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,PAUSE_END,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,SKILL_LEVEL_UP,ITEM_UNDO,SKILL_LEVEL_UP,LEVEL_UP,SKILL_LEVEL_UP,ITEM_DESTROYED,...,SKILL_LEVEL_UP,ITEM_DESTROYED,SKILL_LEVEL_UP,ITEM_PURCHASED,ITEM_PURCHASED,BUILDING_KILL,WARD_KILL,ITEM_DESTROYED,WARD_PLACED,CHAMPION_KILL
1,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,ITEM_DESTROYED,WARD_PLACED,ITEM_DESTROYED,WARD_KILL,WARD_PLACED,...,WARD_PLACED,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED
2,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,WARD_PLACED,WARD_PLACED,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED,ITEM_DESTROYED,LEVEL_UP,...,LEVEL_UP,WARD_PLACED,CHAMPION_KILL,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,SKILL_LEVEL_UP,ITEM_DESTROYED
3,NaN,ITEM_PURCHASED,LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,ITEM_PURCHASED,CHAMPION_KILL,LEVEL_UP,WARD_PLACED,SKILL_LEVEL_UP,...,SKILL_LEVEL_UP,WARD_PLACED,CHAMPION_KILL,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,WARD_KILL,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED
4,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,ITEM_PURCHASED,CHAMPION_SPECIAL_KILL,ITEM_PURCHASED,ELITE_MONSTER_KILL,ITEM_DESTROYED,...,WARD_PLACED,WARD_PLACED,LEVEL_UP,ITEM_PURCHASED,SKILL_LEVEL_UP,WARD_PLACED,BUILDING_KILL,ITEM_PURCHASED,WARD_PLACED,BUILDING_KILL
5,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,LEVEL_UP,WARD_PLACED,...,ITEM_DESTROYED,WARD_PLACED,WARD_PLACED,ITEM_UNDO,WARD_PLACED,CHAMPION_KILL,WARD_KILL,WARD_PLACED,WARD_PLACED,WARD_PLACED
6,NaN,ITEM_PURCHASED,LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,ITEM_PURCHASED,ITEM_PURCHASED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,ITEM_DESTROYED,...,ITEM_PURCHASED,WARD_PLACED,CHAMPION_KILL,ITEM_PURCHASED,WARD_PLACED,LEVEL_UP,LEVEL_UP,WARD_PLACED,WARD_PLACED,CHAMPION_KILL
7,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,LEVEL_UP,WARD_PLACED,ITEM_DESTROYED,ITEM_PURCHASED,ITEM_PURCHASED,WARD_PLACED,WARD_PLACED,...,CHAMPION_KILL,ITEM_DESTROYED,CHAMPION_KILL,ITEM_UNDO,WARD_PLACED,WARD_PLACED,WARD_PLACED,WARD_PLACED,LEVEL_UP,CHAMPION_SPECIAL_KILL
8,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,LEVEL_UP,LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,ITEM_DESTROYED,ITEM_DESTROYED,CHAMPION_KILL,...,CHAMPION_KILL,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,WARD_PLACED,SKILL_LEVEL_UP,LEVEL_UP,ITEM_PURCHASED,SKILL_LEVEL_UP,GAME_END
9,NaN,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED,LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,ITEM_PURCHASED,WARD_PLACED,ITEM_PURCHASED,...,LEVEL_UP,ITEM_DESTROYED,SKILL_LEVEL_UP,ITEM_UNDO,WARD_PLACED,WARD_PLACED,ELITE_MONSTER_KILL,WARD_PLACED,ITEM_SOLD,NaN
10,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,WARD_PLACED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,...,SKILL_LEVEL_UP,ITEM_PURCHASED,CHAMPION_KILL,ITEM_PURCHASED,WARD_PLACED,BUILDING_KILL,SKILL_LEVEL_UP,CHAMPION_KILL,WARD_KILL,NaN
11,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,CHAMPION_KILL,ITEM_PURCHASED,SKILL_LEVEL_UP,ITEM_PURCHASED,...,ITEM_DESTROYED,WARD_KILL,CHAMPION_SPECIAL_KILL,LEVEL_UP,CHAMPION_KILL,CHAMPION_KILL,WARD_PLACED,CHAMPION_KILL,WARD_PLACED,NaN
12,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,LEVEL_UP,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED,...,ITEM_PURCHASED,ITEM_PURCHASED,CHAMPION_KILL,ITEM_SOLD,LEVEL_UP,WARD_PLACED,SKILL_LEVEL_UP,BUILDING_KILL,WARD_PLACED,NaN
13,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,SKILL_LEVEL_UP,WARD_PLACED,SKILL_LEVEL_UP,LEVEL_UP,...,WARD_PLACED,WARD_KILL,ITEM_DESTROYED,SKILL_LEVEL_UP,CHAMPION_KILL,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,CHAMPION_KILL,NaN
14,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,SKILL_LEVEL_UP,ITEM_DESTROYED,ITEM_DESTROYED,ITEM_PURCHASED,ITEM_DESTROYED,SKILL_LEVEL_UP,...,WARD_PLACED,ITEM_PURCHASED,ITEM_DESTROYED,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED,WARD_KILL,NaN,ITEM_PURCHASED,NaN
15,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,LEVEL_UP,SKILL_LEVEL_UP,WARD_PLACED,ITEM_DESTROYED,ITEM_DESTROYED,ITEM_PURCHASED,...,WARD_KILL,ITEM_PURCHASED,ITEM_PURCHASED,WARD_KILL,SKILL_LEVEL_UP,ITEM_PURCHASED,LEVEL_UP,NaN,CHAMPION_KILL,NaN
16,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,ITEM_DESTROYED,LEVEL_UP,ITEM_DESTROYED,...,ITEM_SOLD,LEVEL_UP,BUILDING_KILL,LEVEL_UP,SKILL_LEVEL_UP,ITEM_PURCHASED,SKILL_LEVEL_UP,NaN,LEVEL_UP,NaN
17,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,ITEM_DESTROYED,LEVEL_UP,SKILL_LEVEL_UP,ITEM_PURCHASED,SKILL_LEVEL_UP,LEVEL_UP,...,WARD_PLACED,ITEM_DESTROYED,ITEM_PURCHASED,SKILL_LEVEL_UP,CHAMPION_KILL,WARD_KILL,WARD_PLACED,NaN,WARD_PLACED,NaN
18,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,NaN,ITEM_PURCHASED,ITEM_DESTROYED,ITEM_PURCHASED,...,WARD_PLACED,SKILL_LEVEL_UP,ITEM_DESTROYED,WARD_PLACED,CHAMPION_SPECIAL_KILL,WARD_PLACED,CHAMPION_KILL,NaN,CHAMPION_KILL,NaN
19,NaN,ITEM_PURCHASED,NaN,ITEM_DESTROYED,WARD_PLACED,ITEM_DESTROYED,NaN,LEVEL_UP,LEVEL_UP,WARD_PLACED,...,ITEM_DESTROYED,WARD_PLACED,ITEM_PURCHASED,ITEM_DESTROYED,WARD_PLACED,WARD_PLACED,WARD_PLACED,NaN,CHAMPION_SPECIAL_KILL,NaN
20,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,ITEM_DESTROYED,WARD_KILL,NaN,ITEM_PURCHASED,LEVEL_UP,SKILL_LEVEL_UP,...,ITEM_DESTROYED,WARD_PLACED,WARD_PLACED,WARD_PLACED,CHAMPION_KILL,ITEM_DESTROYED,CHAMPION_KILL,NaN,LEVEL_UP,NaN
21,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,LEVEL_UP,LEVEL_UP,NaN,SKILL_LEVEL_UP,SKILL_LEVEL_UP,LEVEL_UP,...,ITEM_DESTROYED,WARD_PLACED,CHAMPION_KILL,LEVEL_UP,CHAMPION_KILL,WARD_PLACED,LEVEL_UP,NaN,LEVEL_UP,NaN
22,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,LEVEL_UP,WARD_PLACED,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,SKILL_LEVEL_UP,...,ITEM_PURCHASED,LEVEL_UP,LEVEL_UP,WARD_KILL,LEVEL_UP,WARD_PLACED,CHAMPION_KILL,NaN,OBJECTIVE_BOUNTY_PRESTART,NaN
23,NaN,ITEM_PURCHASED,NaN,LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,NaN,WARD_PLACED,LEVEL_UP,ITEM_DESTROYED,...,ITEM_DESTROYED,LEVEL_UP,CHAMPION_KILL,WARD_PLACED,WARD_KILL,WARD_KILL,LEVEL_UP,NaN,SKILL_LEVEL_UP,NaN
24,NaN,ITEM_PURCHASED,NaN,ITEM_DESTROYED,SKILL_LEVEL_UP,ITEM_PURCHASED,NaN,ITEM_PURCHASED,LEVEL_UP,ITEM_DESTROYED,...,ITEM_PURCHASED,SKILL_LEVEL_UP,CHAMPION_SPECIAL_KILL,SKILL_LEVEL_UP,SKILL_LEVEL_UP,ITEM_PURCHASED,SKILL_LEVEL_UP,NaN,BUILDING_KILL,NaN
25,NaN,ITEM_PURCHASED,NaN,SKILL_LEVEL_UP,WARD_PLACED,ITEM_PURCHASED,NaN,ITEM_PURCHASED,SKILL_LEVEL_UP,TURRET_PLATE_DESTROYED,...,WARD_KILL,NaN,SKILL_LEVEL_UP,WARD_PLACED,ITEM_DESTROYED,CHAMPION_KILL,SKILL_LEVEL_UP,NaN,SKILL_LEVEL_UP,NaN
26,NaN,SKILL_LEVEL_UP,NaN,WARD_PLACED,WARD_PLACED,LEVEL_UP,NaN,ITEM_DESTROYED,SKILL_LEVEL_UP,LEVEL_UP,...,ITEM_PURCHASED,NaN,ITEM_SOLD,WARD_PLACED,ITEM_PURCHASED,NaN,ITEM_DESTROYED,NaN,SKILL_LEVEL_UP,NaN
27,NaN,ITEM_UNDO,NaN,LEVEL_UP,LEVEL_UP,LEVEL_UP,NaN,WARD_PLACED,ITEM_DESTROYED,SKILL_LEVEL_UP,...,NaN,NaN,ITEM_PURCHASED,ITEM_DESTROYED,LEVEL_UP,NaN,ITEM_PURCHASED,NaN,WARD_PLACED,NaN
28,NaN,ITEM_UNDO,NaN,LEVEL_UP,SKILL_LEVEL_UP,SKILL_LEVEL_UP,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,ITEM_DESTROYED,ITEM_DESTROYED,ITEM_PURCHASED,NaN,ITEM_DESTROYED,NaN,WARD_PLACED,NaN
29,NaN,ITEM_UNDO,NaN,NaN,ITEM_PURCHASED,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,ITEM_DESTROYED,ITEM_PURCHASED,ITEM_DESTROYED,NaN,ITEM_DESTROYED,NaN,WARD_PLACED,NaN
30,NaN,ITEM_PURCHASED,NaN,NaN,ITEM_PURCHASED,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,ITEM_PURCHASED,NaN,ITEM_PURCHASED,NaN,ITEM_PURCHASED,NaN,ITEM_PURCHASED,NaN
31,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,WARD_PLACED,NaN,ITEM_SOLD,NaN,CHAMPION_KILL,NaN
32,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_SOLD,NaN,ITEM_SOLD,NaN,LEVEL_UP,NaN
33,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,...,NaN,NaN,NaN,NaN,SKILL_LEVEL_UP,NaN,ITEM_SOLD,NaN,LEVEL_UP,NaN
34,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,LEVEL_UP,NaN,ITEM_SOLD,NaN,NaN,NaN
35,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN,NaN
36,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,LEVEL_UP,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_SOLD,NaN,NaN,NaN,NaN,NaN
37,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,SKILL_LEVEL_UP,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN
38,NaN,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN,NaN,ITEM_UNDO,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN
39,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,NaN,NaN,NaN
40,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,...,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN
41,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_UNDO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,ITEM_PURCHASED,NaN,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN,NaN,WARD_PLACED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,SKILL_LEVEL_UP,NaN,NaN,NaN,NaN,NaN,CHAMPION_KILL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LEVEL_UP,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ITEM_PURCHASED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ITEM_DESTROYED,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
type_list=[]
pd.DataFrame(pd.DataFrame(df['info']['frames'])['events'].apply(lambda x: type_list.append(pd.DataFrame(x)['type'].unique())))

   events
0    None
1    None
2    None
3    None
4    None
5    None
6    None
7    None
8    None
9    None
10   None
11   None
12   None
13   None
14   None
15   None
16   None
17   None
18   None
19   None
20   None
21   None
22   None
23   None
24   None
25   None
26   None
27   None
28   None
29   None
30   None
31   None
32   None
33   None
34   None
35   None

In [157]:
list(set(np.concatenate(type_list).tolist()))

['BUILDING_KILL',
 'CHAMPION_KILL',
 'OBJECTIVE_BOUNTY_PRESTART',
 'ITEM_UNDO',
 'GAME_END',
 'WARD_PLACED',
 'CHAMPION_SPECIAL_KILL',
 'TURRET_PLATE_DESTROYED',
 'WARD_KILL',
 'ITEM_DESTROYED',
 'PAUSE_END',
 'ITEM_PURCHASED',
 'ITEM_SOLD',
 'SKILL_LEVEL_UP',
 'ELITE_MONSTER_KILL',
 'LEVEL_UP',
 'OBJECTIVE_BOUNTY_FINISH']